### ISSUE TITLE
HTML source is broken

### ISSUE THREAD

**Issue by albertus82** [albertus82/earthquake-bulletin#3]
From 08/10/2019 the HTML source doesn't work anymore because of changes on the GEOFON website:
```
java.lang.IllegalArgumentException: fromIndex(2) > toIndex(-1)
fromIndex(2) > toIndex(-1)
  java.lang.IllegalArgumentException: fromIndex(2) > toIndex(-1)
    at java.util.ArrayList.subListRangeCheck(Unknown Source)
    at java.util.ArrayList.subList(Unknown Source)
    at it.albertus.eqbulletin.service.decode.html.HtmlBulletinDecoder.decode(HtmlBulletinDecoder.java:35)
    at it.albertus.eqbulletin.service.net.HtmlBulletinDownloader.downloadPage(HtmlBulletinDownloader.java:121)
    at it.albertus.eqbulletin.service.net.HtmlBulletinDownloader.download(HtmlBulletinDownloader.java:77)
    at it.albertus.eqbulletin.service.net.HtmlBulletinDownloader.doDownload(HtmlBulletinDownloader.java:56)
    at it.albertus.eqbulletin.service.net.HtmlBulletinDownloader.download(HtmlBulletinDownloader.java:40)
    at it.albertus.eqbulletin.service.GeofonBulletinProvider.getBulletin(GeofonBulletinProvider.java:22)
    at it.albertus.eqbulletin.service.job.SearchJob.run(SearchJob.java:36)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
```
A fix is in progress; in the meanwhile, please switch to RSS source. Thanks.

**Comment by albertus82** [comment]
Fixed in [v2.2.2](https://github.com/albertus82/earthquake-bulletin/releases/tag/v2.2.2), although the **Status** column is not available anymore.
